name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
            - نام: محیط راه‌اندازی Node.js
  موارد استفاده: actions/setup-node@v6.4.0
  با:
    # نسخه مشخصات نسخه مورد استفاده. مثال‌ها: 12.x، 10.15.1، >=10.15.0.
    نسخه گره: # اختیاری
    # فایل حاوی نسخه مشخصات نسخه مورد استفاده. مثال‌ها: package.json، .nvmrc، .node-version، .tool-versions.
    فایل-نسخه-گره: # اختیاری
    # معماری هدف برای استفاده Node. مثال‌ها: x86، x64. به طور پیش‌فرض از معماری سیستم استفاده خواهد کرد.
    معماری: # اختیاری
    # اگر می‌خواهید اقدام، آخرین نسخه موجود که مشخصات نسخه را برآورده می‌کند، بررسی کند، این گزینه را تنظیم کنید.
    بررسی آخرین: # اختیاری
    # رجیستری اختیاری برای تنظیم برای احراز هویت. رجیستری را در سطح پروژه در فایل‌های .npmrc و .yarnrc تنظیم می‌کند و احراز هویت را برای خواندن از env.NODE_AUTH_TOKEN تنظیم می‌کند.
    آدرس رجیستری: # اختیاری
    # محدوده اختیاری برای احراز هویت در برابر ثبت‌های محدوده‌بندی‌شده. هنگام استفاده از رجیستری بسته‌های گیت‌هاب (https://npm.pkg.github.com/) به مالک مخزن ارجاع داده می‌شود.
    محدوده: # اختیاری
    # برای دریافت توزیع‌های گره از نسخه‌های گره استفاده می‌شود. از آنجایی که یک مقدار پیش‌فرض وجود دارد، معمولاً توسط کاربر ارائه نمی‌شود. هنگام اجرای این اقدام در github.com، مقدار پیش‌فرض کافی است. هنگام اجرا در GHES، اگر با محدودیت سرعت مواجه هستید، می‌توانید یک توکن دسترسی شخصی برای github.com ارسال کنید.
    token: # اختیاری، مقدار پیش‌فرض ${{ github.server_url == 'https://github.com' && github.token || '' }} است
    # برای تعیین یک مدیر بسته برای ذخیره‌سازی در دایرکتوری پیش‌فرض استفاده می‌شود. مقادیر پشتیبانی‌شده: npm، yarn، pnpm.
    حافظه پنهان: # اختیاری
    # برای غیرفعال کردن ذخیره‌سازی خودکار، روی false تنظیم کنید. به‌طور پیش‌فرض، ذخیره‌سازی زمانی فعال می‌شود که devEngines.packageManager یا فیلد packageManager سطح بالا در package.json، npm را به‌عنوان مدیر بسته مشخص کند.
    package-manager-cache: # اختیاری، پیش‌فرض درست است
    # برای مشخص کردن مسیر فایل وابستگی استفاده می‌شود: package-lock.json، yarn.lock و غیره. از کاراکترهای wildcard یا لیستی از نام فایل‌ها برای ذخیره‌سازی چندین وابستگی پشتیبانی می‌کند.
    مسیر وابستگی به حافظه پنهان: # اختیاری
    # برای مشخص کردن یک آینه جایگزین برای دانلود فایل‌های باینری Node.js از آن استفاده می‌شود
    آینه: # اختیاری
    # توکنی که به عنوان سرآیند مجوز هنگام دریافت از آینه استفاده می‌شود
    توکن آینه: # اختیاری
          
